name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: IS_PRODUCTION=1 pnpm run build:firebase
        working-directory: ./nuxt-repo
        env:
          FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
          GOOGLE_APPLICATION_CREDENTIALS: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIVE_SITE }}'
          FIREBASE_APP_ID: '${{ vars.FIREBASE_APP_ID }}'
          FIREBASE_APP_NAME: '${{ vars.FIREBASE_APP_NAME }}'
          FIREBASE_AUTH_DOMAIN: '${{ vars.FIREBASE_AUTH_DOMAIN }}'
          FIREBASE_CLIENT_EMAIL: '${{ vars.FIREBASE_CLIENT_EMAIL }}'
          FIREBASE_DB_URL: '${{ vars.FIREBASE_DB_URL }}'
          FIREBASE_STORAGE_BUCKET: '${{ vars.FIREBASE_STORAGE_BUCKET }}'
          FIREBASE_MEASUREMENT_ID: '${{ vars.FIREBASE_MEASUREMENT_ID }}'
          FIREBASE_MESSAGING_SENDER_ID: '${{ vars.FIREBASE_MESSAGING_SENDER_ID }}'
          FIREBASE_PROJECT_ID: '${{ vars.FIREBASE_PROJECT_ID }}'
          GTM_ID: '${{ vars.GTM_ID }}'
          NUXT_POSTMARK_API_KEY: '${{ secrets.POSTMARK_API_KEY }}'
          NUXT_SANITY_PROJECT_ID: '${{ vars.NUXT_SANITY_PROJECT_ID }}'
          NUXT_SANITY_DATASET: '${{ vars.NUXT_SANITY_DATASET }}'
          NUXT_SANITY_API_READ_TOKEN: '${{ secrets.NUXT_SANITY_API_READ_TOKEN }}'
          NUXT_SANITY_STUDIO_URL: '${{ vars.NUXT_SANITY_STUDIO_URL }}'
          SANITY_STUDIO_PREVIEW_URL: '${{ vars.SANITY_STUDIO_PREVIEW_URL }}'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: './web'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIVE_SITE }}'
          channelId: live
          projectId: live-site